
language: python
python:
  - "3.9"

addons:
  firefox: latest
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
env:
  global:
    - DJANGO_SETTINGS_MODULE="Foodplaner.settings.travis"
    - PGUSER=postgres
    - PGPORT=5432
    - PGHOST=localhost
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo services postgresql restart
  - sleep 1
  - postgres --version

# safelist (indicate the only branches to check)
branches:
  only:
    - dev

install:
  - pip install -r requirements.txt

before_script:
  - install-webdrivers --path webdrivers
services:
  - postgresql

script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py test