
language: python
python:
  - "3.9"

addons:
  firefox: latest
  postgresql: '14.0'

# safelist (indicate the only branches to check)
branches:
  only:
    - dev

install:
  - pip install -r requirements.txt

before_script:
   - install-webdrivers --path webdrivers
env:
  global:
    - DJANGO_SETTINGS_MODULE="Foodplaner.settings.travis"

services:
  - postgresql

script:
  - python manage.py test