# Generated by Django 4.0.5 on 2022-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='img_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='serving',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
