# Generated by Django 4.0.5 on 2022-07-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_dish_img_url_dish_ingredients_dish_serving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='notify_sms',
        ),
    ]
