# Generated by Django 4.0.5 on 2022-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_notify_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='time_days',
            field=models.CharField(max_length=120),
        ),
    ]
